apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor-service
  template:
    metadata:
      labels:
        app: processor-service
    spec:
      containers:
        - name: processor-service
          image: processor-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: BROKER_URL
              value: redis://redis:6379/0
            - name: RESULT_BACKEND
              value: redis://redis:6379/1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 20
